Repository influxdata/influxdb-client-python, pull requests merged in 2020-07, with the labels that each got.

#126 chore: added check to code style, added check to correct PyPI documentation
  .circleci/config.yml
  influxdb_client/client/abstract_client.py
  influxdb_client/client/influxdb_client.py
  influxdb_client/client/write_api.py
  influxdb_client/domain/authorization.py
  influxdb_client/domain/check.py
  influxdb_client/domain/check_base.py
  influxdb_client/domain/check_discriminator.py
  influxdb_client/domain/check_view_properties.py
  influxdb_client/domain/dashboard.py
  influxdb_client/domain/deadman_check.py
  influxdb_client/domain/gauge_view_properties.py
  influxdb_client/domain/greater_threshold.py
  influxdb_client/domain/heatmap_view_properties.py
  influxdb_client/domain/histogram_view_properties.py
  influxdb_client/domain/http_notification_endpoint.py
  influxdb_client/domain/http_notification_rule.py
  influxdb_client/domain/lesser_threshold.py
  influxdb_client/domain/markdown_view_properties.py
  influxdb_client/domain/notification_endpoint.py
  influxdb_client/domain/notification_endpoint_base.py
  influxdb_client/domain/notification_endpoint_discriminator.py
  influxdb_client/domain/notification_rule.py
  influxdb_client/domain/notification_rule_base.py
  influxdb_client/domain/pager_duty_notification_endpoint.py
  influxdb_client/domain/pager_duty_notification_rule.py
  influxdb_client/domain/post_notification_rule.py
  influxdb_client/domain/range_threshold.py
  influxdb_client/domain/resource_member.py
  influxdb_client/domain/resource_owner.py
  influxdb_client/domain/scatter_view_properties.py
  influxdb_client/domain/scraper_target_response.py
  influxdb_client/domain/secret_keys_response.py
  influxdb_client/domain/single_stat_view_properties.py
  influxdb_client/domain/slack_notification_endpoint.py
  influxdb_client/domain/slack_notification_rule.py
  influxdb_client/domain/smtp_notification_rule.py
  influxdb_client/domain/table_view_properties.py
  influxdb_client/domain/telegraf.py
  influxdb_client/domain/threshold.py
  influxdb_client/domain/threshold_check.py
  influxdb_client/domain/xy_view_properties.py
  openapi-generator/src/main/java/org/influxdata/codegen/InfluxPythonGenerator.java
  openapi-generator/src/main/resources/python/model.mustache
  scripts/ci-test.sh
  tox.ini
Labels: ci

#125 docs: added GitHub template for Bug report, Feature request, added configuration for Semantic Pull Requests
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE
  .github/semantic.yml
Labels: documentation

#129 docs: update Line Protocol doc url from 1.6 to 1.8
  README.rst
Labels: documentation

#123 fix: fixed serialization of DataFrame with empty (NaN) values, fixed escaping whitespaces, fixed order of tags
  CHANGELOG.md
  influxdb_client/client/write/dataframe_serializer.py
  influxdb_client/client/write_api.py
  tests/test_WriteApiDataFrame.py
Labels: bug

#132 feat: use microseconds resolutions for data points
  CHANGELOG.md
  influxdb_client/client/write/point.py
  tests/test_point.py
Labels: enhancement

#130 fix: use Retry-After header value for Retryable error codes
  CHANGELOG.md
  influxdb_client/client/write_api.py
  tests/test_WriteApiBatching.py
Labels: bug

#136 feat: allows users to skip of verifying SSL certificate
  CHANGELOG.md
  influxdb_client/client/influxdb_client.py
  influxdb_client/client/write_api.py
  tests/server.pem
  tests/test_InfluxDBClient.py
Labels: enhancement
